---
# Place this config in the static folder. It will be included at the root of the
# gh-pages branch. The filter should prevent CircleCI from running on the
# so the job throws an error if it is run at all.

jobs:
  should_not_run:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Notify Deployment
          command: echo "This should not be running" &&  exit 1

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - test:
          filters:
          branches:
            ignore: gh-pages
      - should_not_run
