version: 2.1

# Docker defaults
defaults: &defaults
  docker:
    - image: cimg/node:18.16.1
  working_directory: /mnt/ramdisk/repo

# Jobs
jobs:
  test_and_build:
    <<: *defaults
    steps:
      - checkout
      # Restore Yarn cache (Yarn 3 uses .yarn/cache directory)
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Use local Yarn version
          command: echo "export PATH=$(pwd)/.yarn/releases:$PATH" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      # Save Yarn cache
      - save_cache:
          name: Save Yarn Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build everything including docs
          command: yarn ci:build

# Workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - test_and_build
