---

version: 2.1

parameters:
  # GHA Params are set when the orb is called from a GitHub Action
  # see: https://circleci.com/blog/trigger-circleci-pipeline-github-action/
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  publish-docs: infinitered/publish-docs@0.3

# Docker defaults
defaults: &defaults
  docker:
    - image: cimg/node:18.16.1
  working_directory: /mnt/ramdisk/repo

# Jobs
jobs:
  test_and_build:
    <<: *defaults
    steps:
      - checkout
      # Restore Yarn cache (Yarn 3 uses .yarn/cache directory)
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Use local Yarn version
          command: echo "export PATH=$(pwd)/.yarn/releases:$PATH" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      # Save Yarn cache
      - save_cache:
          name: Save Yarn Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Build modules and packages
          command: yarn ci:build
      - run:
          name: Run tests
          command: yarn test

# Workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - test_and_build
      - publish-docs/build_docs:
          description: "Use MLKit Models in React Native apps"
          git_email: "ci@infinite.red"
          git_username: "Infinite Red CI"
          label: "React Native MLKit"
          project_name: 'react-native-mlkit'
          source_docs_dir: docs
          source_repo_directory: "source"
          target_docs_dir: "docs"
          target_repo: "git@github.com:infinitered/ir-docs.git"
          target_repo_directory: "target"
  release-docs:
    jobs:
      - publish-docs/publish_docs:
          description: "Use MLKit Models in React Native apps"
          git_email: "ci@infinite.red"
          git_username: "Infinite Red CI"
          label: "React Native MLKit"
          project_name: 'react-native-mlkit'
          source_docs_dir: docs
          target_docs_dir: "docs"
          target_repo: "git@github.com:infinitered/ir-docs.git"
          target_repo_directory: "target"
          filters:
            branches:
              only:
                - main
            tags:
              only:
                - '*react-native-mlkit-*[0-9]+\.[0-9]+\.[0-9]+'
