---
on:
  release:
    types: [published]
  push:
    branches:
      - 'ci-test'
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger CircleCI publish-docs pipeline"
        id: react-native-mlkit-publish-docs
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
