---
name: Version or Release

on:
  push:
    branches:
      - main
      - changeset-release/main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version_or_release:
    # This job checks whether any changesets are present in './changesets'
    #
    #  - If changesets are present, it will run 'yarn version' which updates the
    #    Version Packages PR (removing the changesets)
    #
    # -  If no changesets are present then it will run 'yarn release' which will
    #    publish the packages to npm, add version tags, trigger a docs publish
    #    etc.
    #
    name: "Changesets version or release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn ci:build

      - name: Set git user
        run: |
          git config --global user.name "${{secrets.GIT_USERNAME}}"
          git config --global user.email "${{secrets.GIT_EMAIL}}"

      - name: Version Packages or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn release
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


